export const dict = {
  zh: {
    brand: {
      name: '彭田环保',
      sub: 'PT MOMENTUM',
    },
    nav: {
      home: '首页',
      about: '关于我们',
      business: '业务领域',
      insights: '前沿洞察',
      contact: '联系我们',
      ops: '智能运维',
      opsLogin: '智能运维系统登录',
    },
    cta: {
      aiTool: '投资评估',
    },
    lang: {
      zh: '中',
      en: 'EN',
    },
    mobile: {
      official: '公众号 · 申请中',
      channel: '视频号 · 申请中',
    },
    footer: {
      desc: '专注光伏、风电、储能电站的投资、并购与运营。',
      icp: '沪ICP备18046078号-1',
      copyright: '© 2026 海南彭田环保科技有限公司',
      headings: {
        navigate: '导航 / NAVIGATE',
        business: '业务 / BUSINESS',
        follow: '关注我们 / FOLLOW',
      },
      biz: {
        invest: '新能源投资',
        ma: '电站并购',
        ops: '智慧运营',
        aiTool: '投资评估',
        insights: '前沿技术洞察',
      },
      qr: {
        official: '公众号',
        channel: '视频号',
        pending: '申请中',
      },
      legal: {
        statement: '法律声明',
        privacy: '隐私政策',
        disclaimer: '免责声明',
      },
      slogan: 'POWERING THE DISTRIBUTED FUTURE',
    },
    shared: {
      ctaTitle: '让每一个能源决策，都有据可依',
      ctaDesc: '免费使用投资评估工具，或与我们的投资团队预约一次项目洽谈。',
      ctaEval: '免费使用投资评估',
      ctaBook: '预约项目洽谈',
      disclaimer: '本结果由模型自动生成，仅供参考，不构成任何投资建议。',
      viewAll: '查看全部',
      qrHint: '扫码关注 · 即将开通',
      backTop: '回到顶部',
      stubBody: '本页面内容正在建设中，敬请期待。您可先体验全站开放的投资评估工具，或浏览首页了解彭田环保的业务版图。',
    },
  },
  en: {
    brand: {
      name: 'PT Momentum',
      sub: 'PT MOMENTUM',
    },
    nav: {
      home: 'Home',
      about: 'About Us',
      business: 'Our Business',
      insights: 'Insights',
      contact: 'Contact Us',
      ops: 'Smart O&M',
      opsLogin: 'Smart O&M System Login',
    },
    cta: {
      aiTool: 'Investment Assessment',
    },
    lang: {
      zh: '中',
      en: 'EN',
    },
    mobile: {
      official: 'Official Account · Coming Soon',
      channel: 'Video Channel · Coming Soon',
    },
    footer: {
      desc: 'Focused on the investment, M&A, and operation of distributed PV, wind, and energy storage power stations.',
      icp: '沪ICP备18046078号-1',
      copyright: '© 2026 Hainan Pengtian Environmental Protection Technology Co., Ltd.',
      headings: {
        navigate: 'NAVIGATE',
        business: 'BUSINESS',
        follow: 'FOLLOW US',
      },
      biz: {
        invest: 'New Energy Investment',
        ma: 'Power Plant M&A',
        ops: 'Smart Operations',
        aiTool: 'Investment Assessment',
        insights: 'Frontier Tech Insights',
      },
      qr: {
        official: 'Official Account',
        channel: 'Video Channel',
        pending: 'Coming Soon',
      },
      legal: {
        statement: 'Legal Notice',
        privacy: 'Privacy Policy',
        disclaimer: 'Disclaimer',
      },
      slogan: 'POWERING THE DISTRIBUTED FUTURE',
    },
    shared: {
      ctaTitle: 'Every energy decision, backed by data',
      ctaDesc: 'Try our free investment assessment tool, or book a project consultation with our investment team.',
      ctaEval: 'Free Assessment',
      ctaBook: 'Book a Consultation',
      disclaimer: 'This result is automatically generated by an AI model. It is for reference only and does not constitute investment advice.',
      viewAll: 'View All',
      qrHint: 'Scan to follow · Coming soon',
      backTop: 'Back to top',
      stubBody: 'This page is under construction. In the meantime, try our free investment assessment tool or visit the homepage to explore our business landscape.',
    },
  },
} as const
